### ISSUE TITLE
feat: todo things about `envoy Lua API`

### ISSUE THREAD

**Issue by membphis** [api7/envoy-apisix#18]
- [ ]  regex:  support regular matching.
        - [ ]  Create issue at Envoy, discuss with community
        - [ ]  Schedule
        - [ ]  Integrated into apisix.core
        - [ ]  migrate the plugin from APISIX to Envoy
    - [ ]  `envoy.timer`
    - [ ]  `share dict`
    - [ ]  `cosocket`
    - [ ]  FFI
    
Sort by priority

**Comment by membphis** [comment]
@spacewander @tokers @nic-chen
